import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my certifications',
  projects: [
    {
      id: getId(),
      name: 'Achieving Advanced Insights with BigQuery',
      url: 'https://www.coursera.org/account/accomplishments/certificate/E7DX3R8M4DN4',
      img: '/project-pics/dsa.jpg',
      year: 2022,
      tags: ['DSA', 'Algorithms', 'Problem Solving'],
    },
    {
      id: getId(),
      name: 'Creating New BigQuery Datasets and Visualizing Insights',
      url: 'https://www.coursera.org/account/accomplishments/certificate/YFK6Z8H6NFEU',
      img: '/project-pics/dbms.png',
      year: 2022,
      tags: ['SQL', 'Database Design', 'RDBMS'],
    },
    {
      id: getId(),
      name: 'Applying Machine Learning to your Data with Google Cloud',
      url: 'https://www.coursera.org/account/accomplishments/certificate/T6K6GFQJFLFX',
      img: '/project-pics/ai.png',
      year: 2022,
      tags: ['AI', 'ML', 'Python'],
    },
    {
      id: getId(),
      name: 'Exploring and Preparing your Data with BigQuery',
      url: 'https://www.coursera.org/account/accomplishments/certificate/3MKR4VBHZL4E',
      img: '/project-pics/web-dev.jpeg',
      year: 2022,
      tags: ['SDLC', 'Project Management', 'Agile'],
    },
    {
      id: getId(),
      name: 'From Data to Insights with Google Cloud Specialization',
      url: 'https://www.coursera.org/account/accomplishments/specialization/certificate/AGT3HDEQS8E8',
      img: '/project-pics/java.jpg',
      year: 2022,
      tags: ['Python', 'OOP', 'Software Development'],
    },
    {
      id: getId(),
      name: 'HTML, CSS, and Javascript for Web Developers',
      url: 'https://www.coursera.org/account/accomplishments/certificate/EBKPZJACNPUF',
      img: '/project-pics/software-engineering.jpeg',
      year: 2020,
      tags: ['HTML', 'CSS', 'JavaScript', 'Web Development'],
    },
    {
      id: getId(),
      name: 'Crash Course on Python',
      url: 'https://www.coursera.org/account/accomplishments/certificate/XSWRKN8TFTNF',
      img: '/project-pics/problem-solving.png',
      year: 2020,
      tags: ['Problem Solving', 'Coding', 'Python Programming'],
    },
    {
      id: getId(),
      name: 'Using Python to Access Web Data',
      url: 'https://www.coursera.org/account/accomplishments/certificate/S5NWZKAUHAUN',
      img: '/project-pics/daa.jpg',
      year: 2020,
      tags: ['Algorithms', 'Optimization', 'Complexity Analysis'],
    },
    {
      id: getId(),
      name: 'Programming for Everybody (Getting Started with Python)',
      url: 'https://www.coursera.org/account/accomplishments/certificate/SRDUJPRRW6A6',
      img: '/project-pics/ds-python.jpg',
      year: 2020,
      tags: ['Python', 'Data Science', 'Visualization'],
    },
    {
      id: getId(),
      name: 'Python Data Structures',
      url: 'https://www.coursera.org/account/accomplishments/certificate/ZHWGJ4TUPCF8',
      img: '/project-pics/web-tech.png',
      year: 2020,
      tags: ['Python', 'OOP', 'Software Development'],
    },
  ],
};
