import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my certifications',
  projects: [
    {
      id: getId(),
      name: 'Data Structures and Algorithms',
      img: '/project-pics/dsa.jpg',
      year: 2023,
      tags: ['DSA', 'Algorithms', 'Problem Solving'],
    },
    {
      id: getId(),
      name: 'Database Management System',
      img: '/project-pics/dbms.png',
      year: 2023,
      tags: ['SQL', 'Database Design', 'RDBMS'],
    },
    {
      id: getId(),
      name: 'Artificial Intelligence',
      img: '/project-pics/ai.png',
      year: 2023,
      tags: ['AI', 'ML', 'Python'],
    },
    {
      id: getId(),
      name: 'HTML, CSS, and JavaScript for Web Developers',
      img: '/project-pics/web-dev.jpeg',
      year: 2023,
      tags: ['HTML', 'CSS', 'JavaScript', 'Web Development'],
    },
    {
      id: getId(),
      name: 'Java Programming',
      img: '/project-pics/java.jpg',
      year: 2023,
      tags: ['Java', 'OOP', 'Software Development'],
    },
    {
      id: getId(),
      name: 'Software Engineering',
      img: '/project-pics/software-engineering.jpeg',
      year: 2023,
      tags: ['SDLC', 'Project Management', 'Agile'],
    },
    {
      id: getId(),
      name: 'Programming for Problem Solving',
      img: '/project-pics/problem-solving.png',
      year: 2023,
      tags: ['Problem Solving', 'Coding', 'C Programming'],
    },
    {
      id: getId(),
      name: 'Design and Analysis of Algorithms',
      img: '/project-pics/daa.jpg',
      year: 2023,
      tags: ['Algorithms', 'Optimization', 'Complexity Analysis'],
    },
    {
      id: getId(),
      name: 'Data Science Using Python',
      img: '/project-pics/ds-python.jpg',
      year: 2023,
      tags: ['Python', 'Data Science', 'Visualization'],
    },
    {
      id: getId(),
      name: 'Web Technologies',
      img: '/project-pics/web-tech.png',
      year: 2023,
      tags: ['HTML', 'CSS', 'JavaScript', 'React'],
    },
    {
      id: getId(),
      name: 'Introduction to Machine Learning',
      img: '/project-pics/ml-intro.jpg',
      year: 2023,
      tags: ['ML', 'Python', 'Supervised Learning'],
    },
    {
      id: getId(),
      name: 'Secure Web App Development',
      img: '/project-pics/secure-web-dev.jpeg',
      year: 2023,
      tags: ['Security', 'Web Development', 'OWASP'],
    },
    {
      id: getId(),
      name: 'Computer Algorithms',
      img: '/project-pics/computer-algorithms.jpg',
      year: 2023,
      tags: ['Algorithms', 'DSA', 'Optimization'],
    },
    {
      id: getId(),
      name: 'Data Warehousing and Data Mining',
      img: '/project-pics/data-warehousing.jpg',
      year: 2023,
      tags: ['Data Mining', 'ETL', 'Big Data'],
    },
    {
      id: getId(),
      name: 'Cloud Computing',
      img: '/project-pics/cloud.jpeg',
      year: 2023,
      tags: ['Cloud', 'AWS', 'Azure', 'GCP'],
    },
  ],
};
